# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget CCalib::random_pattern_generator CCalib::omni_calibration CCalib::omni_stereo_calibration CCalib::multi_cameras_calibration)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target CCalib::random_pattern_generator
add_executable(CCalib::random_pattern_generator IMPORTED)

set_target_properties(CCalib::random_pattern_generator PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/hvh/Self_Study/Robotics/Computer_Vision/ccalib/include"
)

# Create imported target CCalib::omni_calibration
add_executable(CCalib::omni_calibration IMPORTED)

set_target_properties(CCalib::omni_calibration PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/hvh/Self_Study/Robotics/Computer_Vision/ccalib/include"
)

# Create imported target CCalib::omni_stereo_calibration
add_executable(CCalib::omni_stereo_calibration IMPORTED)

set_target_properties(CCalib::omni_stereo_calibration PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/hvh/Self_Study/Robotics/Computer_Vision/ccalib/include"
)

# Create imported target CCalib::multi_cameras_calibration
add_executable(CCalib::multi_cameras_calibration IMPORTED)

set_target_properties(CCalib::multi_cameras_calibration PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/hvh/Self_Study/Robotics/Computer_Vision/ccalib/include"
)

# Import target "CCalib::random_pattern_generator" for configuration "Debug"
set_property(TARGET CCalib::random_pattern_generator APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CCalib::random_pattern_generator PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/hvh/Self_Study/Robotics/Computer_Vision/ccalib/build/random_pattern_generator"
  )

# Import target "CCalib::omni_calibration" for configuration "Debug"
set_property(TARGET CCalib::omni_calibration APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CCalib::omni_calibration PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/hvh/Self_Study/Robotics/Computer_Vision/ccalib/build/omni_calibration"
  )

# Import target "CCalib::omni_stereo_calibration" for configuration "Debug"
set_property(TARGET CCalib::omni_stereo_calibration APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CCalib::omni_stereo_calibration PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/hvh/Self_Study/Robotics/Computer_Vision/ccalib/build/omni_stereo_calibration"
  )

# Import target "CCalib::multi_cameras_calibration" for configuration "Debug"
set_property(TARGET CCalib::multi_cameras_calibration APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CCalib::multi_cameras_calibration PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/hvh/Self_Study/Robotics/Computer_Vision/ccalib/build/multi_cameras_calibration"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
